/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Staff = React.memo(function Staff(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/staff-transformed.glb");
  const modelRef = useRef();

  useFrame(() => {
    modelRef.current.rotation.y += 0.007;
  });

  return (
    <group
      {...props}
      dispose={null}
      scale={[0.5, 0.8, 0.5]}
      position={[0.6, -1.6, 0]}
      ref={modelRef}
    >
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials.ZombieSword}
          skeleton={nodes.Object_45.skeleton}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
});

export default Staff;
useGLTF.preload("/models/staff-transformed.glb");
