/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const Wizard = React.memo(function Wizard(props) {
  // Use React.memo for performance optimization
  const { nodes, materials } = useGLTF("/models/wizard-transformed.glb");

  const modelRef = useRef();

  useFrame((state) => {
    modelRef.current.position.y =
      -2.1 + Math.sin(state.clock.elapsedTime) * 0.15;
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      position={[0.1, -2.1, -0.1]}
      scale={[6.26, 4.98, 1.42]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0014rip_mat0136_0.geometry}
        material={materials["mat0.136"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0015rip_mat0137_0.geometry}
        material={materials["mat0.137"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0016rip_mat0138_0.geometry}
        material={materials["mat0.138"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0017rip_mat0139_0.geometry}
        material={materials["mat0.139"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0018rip_mat0140_0.geometry}
        material={materials["mat0.140"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0025rip_mat0147_0.geometry}
        material={materials["mat0.147"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_0045rip_mat0167_0.geometry}
        material={materials["mat0.167"]}
        rotation={[-Math.PI / 2, 0, -0.538]}
      />
    </group>
  );
});

export default Wizard;
useGLTF.preload("/models/wizard-transformed.glb");
